<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.1.0" />
    <PackageReference Include="xunit" Version="2.4.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.3">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="coverlet.collector" Version="3.1.2">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Phoenix.Core\Phoenix.Core.csproj" />
    <ProjectReference Include="..\Phoenix.Archaeology\Phoenix.Archaeology.csproj" />
    <ProjectReference Include="..\Phoenix.Dependency\Phoenix.Dependency.csproj" />
    <ProjectReference Include="..\Phoenix.Environment\Phoenix.Environment.csproj" />
    <ProjectReference Include="..\Phoenix.Build\Phoenix.Build.csproj" />
    <ProjectReference Include="..\Phoenix.Security\Phoenix.Security.csproj" />
    <ProjectReference Include="..\Phoenix.Recovery\Phoenix.Recovery.csproj" />
    <ProjectReference Include="..\Phoenix.Archive\Phoenix.Archive.csproj" />
    <ProjectReference Include="..\Phoenix.Agents\Phoenix.Agents.csproj" />
    <ProjectReference Include="..\Phoenix.Providers\Phoenix.Providers.csproj" />
  </ItemGroup>

</Project>
